environment:
  nodejs_version: "10"
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

platform: x64

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build_script:
  - yarn release -w
  - yarn release-china -w

test: off
