name: Build and release

on:
  release:
    types: [created]

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: host

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Install rpmbuild
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install rpm

      - name: Check out repo
        uses: actions/checkout@v1

      - name: Setup build environment
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: pre-release
          github_token: ${{ secrets.github_token }}
          release: true
